<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Maryell Abella &amp; Sarah Kim">
<meta name="dcterms.date" content="2024-11-02">

<title>PS4: Spatial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="ps4_final_files/libs/clipboard/clipboard.min.js"></script>
<script src="ps4_final_files/libs/quarto-html/quarto.js"></script>
<script src="ps4_final_files/libs/quarto-html/popper.min.js"></script>
<script src="ps4_final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ps4_final_files/libs/quarto-html/anchor.min.js"></script>
<link href="ps4_final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ps4_final_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ps4_final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ps4_final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ps4_final_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">
\RecustomVerbatimEnvironment{verbatim}{Verbatim}{
  showspaces = false,
  showtabs = false,
  breaksymbolleft={},
  breaklines
}

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PS4: Spatial</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Maryell Abella &amp; Sarah Kim </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 2, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>PS4:</strong> Due Sat Nov 2 at 5:00PM Central. Worth 100 points.</p>
<section id="style-points-10-pts" class="level2">
<h2 class="anchored" data-anchor-id="style-points-10-pts">Style Points (10 pts)</h2>
</section>
<section id="submission-steps-10-pts" class="level2">
<h2 class="anchored" data-anchor-id="submission-steps-10-pts">Submission Steps (10 pts)</h2>
<ol type="1">
<li>This problem set is a paired problem set.</li>
<li>Play paper, scissors, rock to determine who goes first. Call that person Partner 1. • Partner 1 (name and cnet ID): Maryell Abella, maryell • Partner 2 (name and cnet ID): Sarah Kim, sarahk1</li>
<li>Partner 1 will accept the ps4 and then share the link it creates with their partner. You can only share it with one partner so you will not be able to change it after your partner has accepted.</li>
<li>“This submission is our work alone and complies with the 30538 integrity policy.” Add your initials to indicate your agreement: <strong>MA</strong> <strong>SK</strong></li>
<li>“I have uploaded the names of anyone else other than my partner and I worked with on the problem set here” (1 point)</li>
<li>Late coins used this pset: <strong>0</strong> Late coins left after submission: <strong>4</strong></li>
<li>Knit your ps4.qmd to an PDF file to make ps4.pdf, • The PDF should not be more than 25 pages. Use head() and re-size figures when appropriate.</li>
<li>(Partner 1): push ps4.qmd and ps4.pdf to your github repo.</li>
<li>(Partner 1): submit ps4.pdf via Gradescope. Add your partner on Gradescope.</li>
<li>(Partner 1): tag your submission in Gradescope</li>
</ol>
<p>Policy Background Hospital closures have been on the rise in recent years. A hospital closure can have significant public health implications as they can increase travel distances for patients and reduce access to critical care, especially for already-vulnerable populations. Before starting, please read this issue brief from the Kaiser Family Foundation (link) to understand the broader social and policy context. We will first look at closures nationally and then focus on Texas, a state with large urban metro areas but also with a substantial share of population living in</p>
</section>
<section id="download-and-explore-the-provider-of-services-pos-file-10-pts" class="level2">
<h2 class="anchored" data-anchor-id="download-and-explore-the-provider-of-services-pos-file-10-pts">Download and explore the Provider of Services (POS) file (10 pts)</h2>
<div id="fb9a8b3a" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> altair <span class="im">as</span> alt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>alt.renderers.enable(<span class="st">"png"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> shapely.geometry <span class="im">import</span> Polygon</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="1">
<li>(Partner 1) This is a fairly large dataset and we won’t be using most of the variables. Read through the rest of the problem set and look through the data dictionary to identify which variables you will need to complete the exercise, and use the tool on data.cms.gov into restrict to those variables (“Manage Columns”) before exporting (“Export”). Download this for 2016 and call it pos2016.csv. What are the variables you pulled?</li>
</ol>
<p>The variables pulled were: Categories: PRVDR_CTGRY_SBTYP_CD Identifies the subtype of the provider. Type of Provider: PRVDR_CTGRY_CD Identifies the type of provider. CMS certification number: PRVDR_NUM CMS certification number, unique for each hospital. Termination Code: PGM_TRMNTN_CD Indicates the current termination status for the provider. Termination Date: TRMNTN_EXPRTN_DT Date the provider was terminated. Facility Name: FAC_NAME Zip Code: ZIP_CD State Code: STATE_CD</p>
<ol start="2" type="1">
<li>(Partner 1) Import your pos2016.csv file. We want to focus on short-term hospitals. These are identified as facilities with provider type code 01 and subtype code 01. Subset your data to these facilities.</li>
</ol>
<ol type="a">
<li>How many hospitals are reported in this data?</li>
</ol>
<div id="0db0b532" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>path <span class="op">=</span> <span class="vs">r'/Users/maryell/Desktop/problem-set-4-maryell-sarah/'</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#path = r'/Users/sarahkim/Documents/Coding/'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fbba4a5a" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>file_2016 <span class="op">=</span> <span class="st">'pos2016.csv'</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>absolute_path_2016 <span class="op">=</span> os.path.join(path, file_2016)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>df_2016 <span class="op">=</span> pd.read_csv(absolute_path_2016)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>short_hospitals_2016 <span class="op">=</span> df_2016[(df_2016[<span class="st">'PRVDR_CTGRY_CD'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    df_2016[<span class="st">'PRVDR_CTGRY_SBTYP_CD'</span>] <span class="op">==</span> <span class="dv">1</span>)]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>hospitals_2016 <span class="op">=</span> short_hospitals_2016.shape[<span class="dv">0</span>]</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>hospitals_2016</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>7245</code></pre>
</div>
</div>
<p>There are 7,245 hospitals reported through this data set in 2016.</p>
<ol start="2" type="a">
<li>Does this number make sense? Cross-reference with other sources and cite the number you compared it to. If it differs, why do you think it could differ?</li>
</ol>
<div id="0d89cbc1" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(short_hospitals_2016.nunique())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>PRVDR_CTGRY_SBTYP_CD       1
PRVDR_CTGRY_CD             1
FAC_NAME                6770
PRVDR_NUM               7245
STATE_CD                  56
PGM_TRMNTN_CD              8
TRMNTN_EXPRTN_DT        1895
ZIP_CD                  5676
dtype: int64</code></pre>
</div>
</div>
<p>The American Hospital Association states that there are currently around 6,120 hospitals in the US. Data.cms.gov shows 5,394 rows of instances for hospitals. Statistica claims there were 6,140 hospitals in 2016. This differs from the number we previously obtained, 7,245. However, it seems to more closely match the instances of different facility names, 6,770. This may be due to varying errors in reporting or obtaining the data, especially as organizations may use different criterias to distinguish a hospital. The definitions of a hospital can vary, leading to inconsistencies in the data.</p>
<p>#https://www.aha.org/statistics/fast-facts-us-hospitals #https://data.cms.gov/provider-data/dataset/xubh-q36u #https://www.statista.com/statistics/195240/number-of-medicare-hospital-facilities-in-the-us/</p>
<ol start="3" type="1">
<li>(Partner 1) Repeat the previous 3 steps with 2017Q4, 2018Q4, and 2019Q4 and then append them together. Plot the number of observations in your dataset by year.</li>
</ol>
<div id="38cfe720" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>file_2017 <span class="op">=</span> <span class="st">'pos2017.csv'</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>absolute_path_2017 <span class="op">=</span> os.path.join(path, file_2017)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>df_2017 <span class="op">=</span> pd.read_csv(absolute_path_2017)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>short_hospitals_2017 <span class="op">=</span> df_2017[(df_2017[<span class="st">'PRVDR_CTGRY_CD'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    df_2017[<span class="st">'PRVDR_CTGRY_SBTYP_CD'</span>] <span class="op">==</span> <span class="dv">1</span>)]</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>hospitals_2017 <span class="op">=</span> short_hospitals_2017.shape[<span class="dv">0</span>]</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>hospitals_2017</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>7260</code></pre>
</div>
</div>
<div id="f68701f7" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>file_2018 <span class="op">=</span> <span class="st">'pos2018.csv'</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>absolute_path_2018 <span class="op">=</span> os.path.join(path, file_2018)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">"""Fixing issue with text encoding"""</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>df_2018 <span class="op">=</span> pd.read_csv(absolute_path_2018, encoding<span class="op">=</span><span class="st">'ISO-8859-1'</span>)  </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>short_hospitals_2018 <span class="op">=</span> df_2018[(df_2018[<span class="st">'PRVDR_CTGRY_CD'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    df_2018[<span class="st">'PRVDR_CTGRY_SBTYP_CD'</span>] <span class="op">==</span> <span class="dv">1</span>)]</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>hospitals_2018 <span class="op">=</span> short_hospitals_2018.shape[<span class="dv">0</span>]</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>hospitals_2018</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co">#https://stackoverflow.com/questions/30462807/encoding-error-in-panda-read-csv</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>7277</code></pre>
</div>
</div>
<div id="3df1c38f" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>file_2019 <span class="op">=</span> <span class="st">'pos2019.csv'</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>absolute_path_2019 <span class="op">=</span> os.path.join(path, file_2019)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co">"""Fixing issue with text encoding"""</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>df_2019 <span class="op">=</span> pd.read_csv(absolute_path_2019, encoding<span class="op">=</span><span class="st">'ISO-8859-1'</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>short_hospitals_2019 <span class="op">=</span> df_2019[(df_2019[<span class="st">'PRVDR_CTGRY_CD'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    df_2019[<span class="st">'PRVDR_CTGRY_SBTYP_CD'</span>] <span class="op">==</span> <span class="dv">1</span>)]</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>hospitals_2019 <span class="op">=</span> short_hospitals_2019.shape[<span class="dv">0</span>]</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>hospitals_2019</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>7303</code></pre>
</div>
</div>
<div id="44a98375" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""List to append data"""</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>all_hospitals <span class="op">=</span> []</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">"""Adding year column to each dataframe"""</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>short_hospitals_2016[<span class="st">'Year'</span>] <span class="op">=</span> <span class="dv">2016</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>all_hospitals.append(short_hospitals_2016)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>short_hospitals_2017[<span class="st">'Year'</span>] <span class="op">=</span> <span class="dv">2017</span> </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>all_hospitals.append(short_hospitals_2017)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>short_hospitals_2018[<span class="st">'Year'</span>] <span class="op">=</span> <span class="dv">2018</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>all_hospitals.append(short_hospitals_2018)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>short_hospitals_2019[<span class="st">'Year'</span>] <span class="op">=</span> <span class="dv">2019</span>  </span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>all_hospitals.append(short_hospitals_2019)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="co">"""Appending"""</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>combined_hospitals <span class="op">=</span> pd.concat(all_hospitals, ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(combined_hospitals.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   PRVDR_CTGRY_SBTYP_CD  PRVDR_CTGRY_CD                          FAC_NAME  \
0                   1.0               1  SOUTHEAST ALABAMA MEDICAL CENTER   
1                   1.0               1            NORTH JACKSON HOSPITAL   
2                   1.0               1     MARSHALL MEDICAL CENTER SOUTH   
3                   1.0               1    ELIZA COFFEE MEMORIAL HOSPITAL   
4                   1.0               1          MIZELL MEMORIAL HOSPITAL   

  PRVDR_NUM STATE_CD  PGM_TRMNTN_CD  TRMNTN_EXPRTN_DT   ZIP_CD  Year  
0    010001       AL              0               NaN  36301.0  2016  
1    010004       AL              1        20010831.0  35740.0  2016  
2    010005       AL              0               NaN  35957.0  2016  
3    010006       AL              0               NaN  35631.0  2016  
4    010007       AL              0               NaN  36467.0  2016  </code></pre>
</div>
</div>
<div id="95d757cb" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Grouping hospitals by year"""</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>hospitals_by_year <span class="op">=</span> combined_hospitals.groupby(<span class="st">'Year'</span>).size().reset_index(name<span class="op">=</span><span class="st">'Count'</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co">"""Bar chart of hospitals by year"""</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>all_hospitals_chart <span class="op">=</span> alt.Chart(hospitals_by_year).mark_bar().encode(</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>alt.X(<span class="st">'Year:O'</span>),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>alt.Y(<span class="st">'Count:Q'</span>),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>).properties(</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">'Number of Observations by Year'</span>,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>all_hospitals_chart</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>
<figure class="figure">
<p><img src="ps4_final_files/figure-html/cell-10-output-1.png" width="212" height="377" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ol start="4" type="1">
<li>Each hospital is identified by its CMS certification number.</li>
</ol>
<ol type="a">
<li>Plot the number of unique hospitals in your dataset per year.</li>
</ol>
<div id="59ae2664" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Grouping by year and provider number"""</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>cms_by_year <span class="op">=</span> combined_hospitals.groupby(<span class="st">'Year'</span>)[<span class="st">'PRVDR_NUM'</span>].nunique(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    ).reset_index(name<span class="op">=</span><span class="st">'CMS Count'</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co">"""Bar chart of hospitals by year and provider number"""</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>cms_hospitals_chart <span class="op">=</span> alt.Chart(cms_by_year).mark_bar().encode(</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>alt.X(<span class="st">'Year:O'</span>),</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>alt.Y(<span class="st">'CMS Count:Q'</span>),</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>).properties(</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">'Number of Unique Hospitals by Year'</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>cms_hospitals_chart</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>
<figure class="figure">
<p><img src="ps4_final_files/figure-html/cell-11-output-1.png" width="236" height="377" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="a">
<li>Compare this to your plot in the previous step. What does this tell you about the structure of the data?</li>
</ol>
<p>As the bar graphs look the same from the previous step, it signifies that the CMS is a unique identifier for hospitals. This ensures the reliability of the CMS data in accurately reflecting the number of distinct hospitals, at least for the definition of hospital this data set provides. It also suggest that the code ensures that hospitals are categorized without duplication. The CMS code is the leading identifier for the structure of this data as the number of observations matches the number of unique hospitals.</p>
</section>
<section id="identify-hospital-closures-in-pos-file-15-pts" class="level2">
<h2 class="anchored" data-anchor-id="identify-hospital-closures-in-pos-file-15-pts">Identify hospital closures in POS file (15 pts) (*)</h2>
<p>We will now use the 2016-2019 files to identify hospital closures nationally. A hospital is suspected to have closed if its Termination Code in the POS file lists them as an “Active Provider” in 2016 and then they are either not active or do not appear in the data at all in a subsequent year.</p>
<ol type="1">
<li>(Partner 2) Use this definition to create a list of all hospitals that were active in 2016 that were suspected to have closed by 2019. Record the facility name and zip of each hospital as well as the year of suspected closure (when they become terminated or disappear from the data). How many hospitals are there that fit this definition?</li>
</ol>
<div id="826e927d" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> combined_closure(combined_hospitals):</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Filtered hospitals that were active in 2016"""</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    active_2016 <span class="op">=</span> combined_hospitals[(combined_hospitals[<span class="st">'Year'</span>] <span class="op">==</span> <span class="dv">2016</span>) <span class="op">&amp;</span> (combined_hospitals[<span class="st">'PGM_TRMNTN_CD'</span>] <span class="op">==</span> <span class="dv">0</span>)]</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    closures <span class="op">=</span> []</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Looped through each active hospital in 2016 to check for any suspected closures"""</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _, hospital <span class="kw">in</span> active_2016.iterrows():</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>        provider_num <span class="op">=</span> hospital[<span class="st">'PRVDR_NUM'</span>]</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>        facility_name <span class="op">=</span> hospital[<span class="st">'FAC_NAME'</span>]</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>        zipcode <span class="op">=</span> hospital[<span class="st">'ZIP_CD'</span>]</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>        is_closed <span class="op">=</span> <span class="va">False</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>        <span class="co">"""Checked 2017, 2018, and 2019 for their active status"""</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> year <span class="kw">in</span> [<span class="dv">2017</span>, <span class="dv">2018</span>, <span class="dv">2019</span>]:</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>            current_year_data <span class="op">=</span> combined_hospitals[</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>                (combined_hospitals[<span class="st">'Year'</span>] <span class="op">==</span> year) <span class="op">&amp;</span> (combined_hospitals[<span class="st">'PRVDR_NUM'</span>] <span class="op">==</span> provider_num)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>            ]</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>            <span class="co">"""Determined if the hsopital has closed"""</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> current_year_data.empty <span class="kw">or</span> current_year_data[<span class="st">'PGM_TRMNTN_CD'</span>].ne(<span class="dv">0</span>).<span class="bu">any</span>():</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>                closures.append([facility_name, zipcode, year])</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>                is_closed <span class="op">=</span> <span class="va">True</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>                <span class="cf">break</span> </span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Created a dataframe from the closures list"""</span></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>    closure_df <span class="op">=</span> pd.DataFrame(closures, columns<span class="op">=</span>[<span class="st">"Facility Name"</span>, <span class="st">"Zipcode"</span>, <span class="st">"Year of Suspected Closure"</span>])</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> closure_df</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>suspected_closures_df <span class="op">=</span> combined_closure(combined_hospitals)</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(suspected_closures_df.head())</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>number_of_closures <span class="op">=</span> suspected_closures_df.shape[<span class="dv">0</span>]</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(number_of_closures)</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a><span class="co">#source: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html</span></span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a><span class="co">#https://realpython.com/python-or-operator/</span></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a><span class="co">#https://www.w3schools.com/python/pandas/ref_df_ne.asp</span></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a><span class="co">#https://www.w3schools.com/python/ref_func_any.asp</span></span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a><span class="co">#https://stackoverflow.com/questions/19828822/how-do-i-check-if-a-pandas-dataframe-is-empty</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       Facility Name  Zipcode  Year of Suspected Closure
0                   WEDOWEE HOSPITAL  36278.0                       2019
1           GEORGIANA MEDICAL CENTER  36033.0                       2019
2                   RMC JACKSONVILLE  36265.0                       2018
3  NORTH ALABAMA SPECIALITY HOSPITAL  35611.0                       2018
4             ABRAZO MARYVALE CAMPUS  85031.0                       2017
174</code></pre>
</div>
</div>
<p>There are 174 hospitals that fit this definition of closure</p>
<ol start="2" type="1">
<li>(Partner 2) Sort this list of hospitals by name and report the names and year of suspected closure for the first 10 rows.</li>
</ol>
<div id="1ee37e3f" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Sorted by alphabetic order and extracted the first ten"""</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>suspected_closures_df.sort_values(by<span class="op">=</span>[<span class="st">'Facility Name'</span>]).head(<span class="dv">10</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co">#source: https://www.geeksforgeeks.org/how-to-sort-pandas-dataframe/</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Facility Name</th>
<th data-quarto-table-cell-role="th">Zipcode</th>
<th data-quarto-table-cell-role="th">Year of Suspected Closure</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>ABRAZO MARYVALE CAMPUS</td>
<td>85031.0</td>
<td>2017</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">10</td>
<td>ADVENTIST MEDICAL CENTER - CENTRAL VALLEY</td>
<td>93230.0</td>
<td>2017</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">97</td>
<td>AFFINITY MEDICAL CENTER</td>
<td>44646.0</td>
<td>2018</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">80</td>
<td>ALBANY MEDICAL CENTER / SOUTH CLINICAL CAMPUS</td>
<td>12208.0</td>
<td>2017</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">140</td>
<td>ALLEGIANCE SPECIALTY HOSPITAL OF KILGORE</td>
<td>75662.0</td>
<td>2017</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">62</td>
<td>ALLIANCE LAIRD HOSPITAL</td>
<td>39365.0</td>
<td>2019</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">101</td>
<td>ALLIANCEHEALTH DEACONESS</td>
<td>73112.0</td>
<td>2019</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">26</td>
<td>ANNE BATES LEACH EYE HOSPITAL</td>
<td>33136.0</td>
<td>2019</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">21</td>
<td>ARKANSAS VALLEY REGIONAL MEDICAL CENTER</td>
<td>81050.0</td>
<td>2017</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">69</td>
<td>BANNER CHURCHILL COMMUNITY HOSPITAL</td>
<td>89406.0</td>
<td>2017</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<ol start="3" type="1">
<li>(Partner 2) However, not all suspected hospital closures are true closures. For example, in the case of a merger, a CMS certification number will be appear to be “terminated,” but then the hospital re-appear under a similar name/address with a new CMS certification number in the next year. As a first pass to address this, remove any suspected hospital closures that are in zip codes where the number of active hospitals does not decrease in the year after the suspected closure.</li>
</ol>
<ol type="i">
<li>Among the suspected closures, how many hospitals fit this definition of potentially being a merger/acquisition? After correcting for this, how many hospitals do you have left?</li>
</ol>
<div id="2b747c14" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> filter_true_closures_with_tracking(suspected_closures, combined_hospitals):</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Converted zip codes to integers """</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    combined_hospitals[<span class="st">'ZIP_CD_INT'</span>] <span class="op">=</span> combined_hospitals[<span class="st">'ZIP_CD'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    suspected_closures[<span class="st">'Zipcode_INT'</span>] <span class="op">=</span> suspected_closures[<span class="st">'Zipcode'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Calculate active hospital counts by year and zip code """</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    active_hospitals <span class="op">=</span> combined_hospitals[combined_hospitals[<span class="st">'PGM_TRMNTN_CD'</span>] <span class="op">==</span> <span class="dv">0</span>].groupby([<span class="st">'Year'</span>, <span class="st">'ZIP_CD_INT'</span>]).size().reset_index(name<span class="op">=</span><span class="st">'Active Hospital Count'</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    true_closures <span class="op">=</span> []</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    potential_mergers <span class="op">=</span> []</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Looped through each suspected closure to check its closure status """</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _, closure <span class="kw">in</span> suspected_closures.iterrows():</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>        zipcode <span class="op">=</span> closure[<span class="st">'Zipcode'</span>]</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>        closure_year <span class="op">=</span> closure[<span class="st">'Year of Suspected Closure'</span>]</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>        current_year_count <span class="op">=</span> active_hospitals[(active_hospitals[<span class="st">'Year'</span>] <span class="op">==</span> closure_year) <span class="op">&amp;</span> (active_hospitals[<span class="st">'ZIP_CD_INT'</span>] <span class="op">==</span> zipcode)][<span class="st">'Active Hospital Count'</span>].values</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>        next_year_count <span class="op">=</span> active_hospitals[(active_hospitals[<span class="st">'Year'</span>] <span class="op">==</span> closure_year <span class="op">+</span> <span class="dv">1</span>) <span class="op">&amp;</span> (active_hospitals[<span class="st">'ZIP_CD_INT'</span>] <span class="op">==</span> zipcode)][<span class="st">'Active Hospital Count'</span>].values</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>        current_year_number <span class="op">=</span> <span class="dv">0</span> </span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">len</span>(current_year_count) <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>            current_year_number <span class="op">=</span> current_year_count[<span class="dv">0</span>]</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>        next_year_number <span class="op">=</span> <span class="dv">0</span> </span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">len</span>(next_year_count) <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>            next_year_number <span class="op">=</span> next_year_count[<span class="dv">0</span>]</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>        <span class="co">"""Determine if the closure is an actual closure or a potential merger"""</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> next_year_number <span class="op">==</span> <span class="dv">0</span> <span class="kw">or</span> current_year_number <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>            true_closures.append(closure)</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>        <span class="cf">elif</span> next_year_number <span class="op">&gt;=</span> current_year_number:</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a>            potential_mergers.append(closure)</span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>: </span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>            true_closures.append(closure)</span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Made a dataframe with the true closures and potential merger lists """</span></span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a>    true_closures_df <span class="op">=</span> pd.DataFrame(true_closures)</span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a>    potential_mergers_df <span class="op">=</span> pd.DataFrame(potential_mergers)</span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> true_closures_df, potential_mergers_df, active_hospitals</span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a>true_suspected_closures_df, potential_mergers_df, active_hospitals <span class="op">=</span> filter_true_closures_with_tracking(suspected_closures_df, combined_hospitals)</span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a>number_of_potential_mergers <span class="op">=</span> potential_mergers_df.shape[<span class="dv">0</span>]</span>
<span id="cb20-46"><a href="#cb20-46" aria-hidden="true" tabindex="-1"></a>number_of_true_closures <span class="op">=</span> true_suspected_closures_df.shape[<span class="dv">0</span>]</span>
<span id="cb20-47"><a href="#cb20-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-48"><a href="#cb20-48" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(number_of_potential_mergers)</span>
<span id="cb20-49"><a href="#cb20-49" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(number_of_true_closures)</span>
<span id="cb20-50"><a href="#cb20-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-51"><a href="#cb20-51" aria-hidden="true" tabindex="-1"></a><span class="co">#source: https://stackoverflow.com/questions/10200268/what-does-shape-do-in-for-i-in-rangey-shape0</span></span>
<span id="cb20-52"><a href="#cb20-52" aria-hidden="true" tabindex="-1"></a><span class="co">#https://www.w3schools.com/python/ref_string_split.asp</span></span>
<span id="cb20-53"><a href="#cb20-53" aria-hidden="true" tabindex="-1"></a><span class="co">#https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.size.html</span></span>
<span id="cb20-54"><a href="#cb20-54" aria-hidden="true" tabindex="-1"></a><span class="co">#https://www.w3schools.com/python/ref_list_append.asp</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>27
147</code></pre>
</div>
</div>
<p>The number of hospitals potentially involved in a merger/acquisition is 27. The number of true hospital closures after filtering is 147.</p>
<ol start="2" type="i">
<li>Sort this list of corrected hospital closures by name and report the first 10 rows.</li>
</ol>
<div id="85bbf697" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Sorted it by alphabetic order and extracted first ten """</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>true_suspected_closures_df.sort_values(by<span class="op">=</span>[<span class="st">'Facility Name'</span>]).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Facility Name</th>
<th data-quarto-table-cell-role="th">Zipcode</th>
<th data-quarto-table-cell-role="th">Year of Suspected Closure</th>
<th data-quarto-table-cell-role="th">Zipcode_INT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>ABRAZO MARYVALE CAMPUS</td>
<td>85031.0</td>
<td>2017</td>
<td>85031</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">97</td>
<td>AFFINITY MEDICAL CENTER</td>
<td>44646.0</td>
<td>2018</td>
<td>44646</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">140</td>
<td>ALLEGIANCE SPECIALTY HOSPITAL OF KILGORE</td>
<td>75662.0</td>
<td>2017</td>
<td>75662</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">62</td>
<td>ALLIANCE LAIRD HOSPITAL</td>
<td>39365.0</td>
<td>2019</td>
<td>39365</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">101</td>
<td>ALLIANCEHEALTH DEACONESS</td>
<td>73112.0</td>
<td>2019</td>
<td>73112</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">26</td>
<td>ANNE BATES LEACH EYE HOSPITAL</td>
<td>33136.0</td>
<td>2019</td>
<td>33136</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">21</td>
<td>ARKANSAS VALLEY REGIONAL MEDICAL CENTER</td>
<td>81050.0</td>
<td>2017</td>
<td>81050</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">69</td>
<td>BANNER CHURCHILL COMMUNITY HOSPITAL</td>
<td>89406.0</td>
<td>2017</td>
<td>89406</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>BANNER PAYSON MEDICAL CENTER</td>
<td>85541.0</td>
<td>2018</td>
<td>85541</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">115</td>
<td>BARIX CLINICS OF PENNSYLVANIA</td>
<td>19047.0</td>
<td>2019</td>
<td>19047</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="download-census-zip-code-shapefile-10-pt" class="level2">
<h2 class="anchored" data-anchor-id="download-census-zip-code-shapefile-10-pt">Download Census zip code shapefile (10 pt)</h2>
<ol type="1">
<li>(Partner 1) This is non-tabular data. What are the five file types? What type of information is in each file? It will be useful going forward to have a sense going forward of which files are big versus small. After unzipping, how big is each of the datasets?</li>
</ol>
<p>The five files are in order of descending file size: 1. .shp (shape file, 837.5 MB): contains the geometric data. 2. .dbf (database file, 6.4 MB): contains attribute data corresponding to the .shp file. 3. .shx (shape index file, 265 KB): contains the index data for the .shp file. 4. .xml (extensible markup language file, 16 KB): which is used to structure the data. 5. .prj (projection file, 165 bytes): contains the coordinate system and projection information corresponding to the .shp file.</p>
<ol start="2" type="1">
<li>(Partner 1) Load the zip code shapefile and restrict to Texas zip codes. (Hint: you can identify which state a zip code is in using the first 2-3 numbers in the zip code (Wikipedia link). Then calculate the number of hospitals per zip code in 2016 based on the cleaned POS file from the previous step. Plot a choropleth of the number of hospitals by zip code in Texas.</li>
</ol>
<div id="06be15db" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Uploading shapefile"""</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>census <span class="op">=</span> <span class="st">'gz_2010_us_860_00_500k.shp'</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>absolute_path_shp <span class="op">=</span> os.path.join(path, census)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>census_shp <span class="op">=</span> gpd.read_file(absolute_path_shp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="013be306" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Texas zipcode prefixes by first 3 digits"""</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>tx_zip_prefixes <span class="op">=</span> [</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'733'</span>, <span class="st">'750'</span>, <span class="st">'751'</span>, <span class="st">'752'</span>, <span class="st">'753'</span>, <span class="st">'754'</span>, <span class="st">'755'</span>, <span class="st">'756'</span>, <span class="st">'757'</span>, </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'758'</span>, <span class="st">'759'</span>, <span class="st">'760'</span>, <span class="st">'761'</span>, <span class="st">'762'</span>, <span class="st">'763'</span>, <span class="st">'764'</span>, <span class="st">'765'</span>, <span class="st">'766'</span>, </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'767'</span>, <span class="st">'768'</span>, <span class="st">'769'</span>, <span class="st">'770'</span>, <span class="st">'771'</span>, <span class="st">'772'</span>, <span class="st">'773'</span>, <span class="st">'774'</span>, <span class="st">'775'</span>, </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'776'</span>, <span class="st">'777'</span>, <span class="st">'778'</span>, <span class="st">'779'</span>, <span class="st">'780'</span>, <span class="st">'781'</span>, <span class="st">'782'</span>, <span class="st">'783'</span>, <span class="st">'784'</span>, </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'785'</span>, <span class="st">'786'</span>, <span class="st">'787'</span>, <span class="st">'788'</span>, <span class="st">'789'</span>, <span class="st">'790'</span>, <span class="st">'791'</span>, <span class="st">'792'</span>, <span class="st">'793'</span>, </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'794'</span>, <span class="st">'795'</span>, <span class="st">'796'</span>, <span class="st">'797'</span>, <span class="st">'798'</span>, <span class="st">'799'</span>, <span class="st">'885'</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="co">"""Isolating Texas zipcodes from the census shapefile"""</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>tx_zip <span class="op">=</span> census_shp[census_shp[<span class="st">'ZCTA5'</span>].<span class="bu">str</span>[:<span class="dv">3</span>].isin(tx_zip_prefixes)]</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="co">"""Texas prefixes by first 3 digits"""</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>hospitals_per_zip <span class="op">=</span> combined_hospitals[combined_hospitals[<span class="st">'Year'</span>] <span class="op">==</span> <span class="dv">2016</span>].groupby(</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ZIP_CD'</span>)[<span class="st">'PRVDR_NUM'</span>].nunique().reset_index(name<span class="op">=</span><span class="st">'Hospital_Count'</span>)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="co">"""Converting both zipcodes to strings to match"""</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>hospitals_per_zip[<span class="st">'ZIP_CD'</span>] <span class="op">=</span> hospitals_per_zip[<span class="st">'ZIP_CD'</span>].astype(<span class="bu">str</span>)</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>tx_zip[<span class="st">'ZCTA5'</span>] <span class="op">=</span> tx_zip[<span class="st">'ZCTA5'</span>].astype(<span class="bu">str</span>)</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="co">"""Merging both dataframes by zipcodes"""</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>tx_zip_hospitals <span class="op">=</span> tx_zip.merge(hospitals_per_zip, left_on<span class="op">=</span><span class="st">'ZCTA5'</span>, right_on<span class="op">=</span><span class="st">'ZIP_CD'</span>, how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>tx_zip_hospitals[<span class="st">'Hospital_Count'</span>] <span class="op">=</span> tx_zip_hospitals[<span class="st">'Hospital_Count'</span>].fillna(<span class="dv">0</span>) </span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>tx_zip_hospitals[<span class="st">'Hospital_Count'</span>] <span class="op">=</span> tx_zip_hospitals[<span class="st">'Hospital_Count'</span>].astype(<span class="bu">int</span>) </span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a><span class="co">#https://pandas.pydata.org/docs/reference/api/pandas.merge.html</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="4dedc6fc" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> tx_zip_hospitals.plot(column<span class="op">=</span><span class="st">'Hospital_Count'</span>, legend<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Number of Hospitals by Zipcode in Texas (2016)'</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">'off'</span>)  </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>plt.show()  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="ps4_final_files/figure-html/cell-18-output-1.png" width="512" height="417" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="calculate-zip-codes-distance-to-the-nearest-hospital-20-pts" class="level2">
<h2 class="anchored" data-anchor-id="calculate-zip-codes-distance-to-the-nearest-hospital-20-pts">Calculate zip code’s distance to the nearest hospital (20 pts) (*)</h2>
<ol type="1">
<li>(Partner 2) Create a GeoDataFrame for the centroid of each zip code nationally: zips_all_centroids. What are the dimensions of the resulting GeoDataFrame? What do each of the columns mean?</li>
</ol>
<div id="2a17ad66" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>census_file <span class="op">=</span> <span class="st">'gz_2010_us_860_00_500k.shp'</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>absolute_path_shp <span class="op">=</span> os.path.join(path, census_file)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>census <span class="op">=</span> gpd.read_file(absolute_path_shp)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co">"""Made a new GeoDataFrame with zip codes and centroid coordinates """</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>census[<span class="st">'centroid'</span>] <span class="op">=</span> census.geometry.centroid</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>zips_all_centroids <span class="op">=</span> gpd.GeoDataFrame(census[[<span class="st">'ZCTA5'</span>, <span class="st">'centroid'</span>]], geometry<span class="op">=</span><span class="st">'centroid'</span>, crs<span class="op">=</span>census.crs)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zips_all_centroids.shape)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zips_all_centroids.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(33120, 2)
Index(['ZCTA5', 'centroid'], dtype='object')</code></pre>
</div>
</div>
<p>The dimensions of zips_all_centroids: (33120, 2) For the columns in zips_all_centroids: Index([‘ZCTA5’, ‘centroid’], dtype=‘object’)</p>
<p>ZCTA5: this represents the zip code tabulation area for each area. It it used to approximate zip codes. centroid: this column contains the centroid geometry for each ZCTA polygon, represented as a point. The centroid is the geographic center of reach ZCTA’s area, calculated based on the shape of the ZIP code boundary.</p>
<ol start="2" type="1">
<li>(Partner 2) Create two GeoDataFrames as subsets of zips_all_centroids. First, create all zip codes in Texas: zips_texas_centroids. Then, create all zip codes in Texas or a bordering state: zips_texas_borderstates_centroids, using the zip code prefixes to make these subsets. How many unique zip codes are in each of these subsets? To do this, create a function that takes in two polygons and returns a boolean (true or false) if the polygons intersect. Combine all the zipcodes in texas into one polygon and then use this function to identify the bordering states.</li>
</ol>
<div id="2b1a0965" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>texas_zc <span class="op">=</span> ( <span class="st">'733'</span>, <span class="st">'750'</span>, <span class="st">'751'</span>, <span class="st">'752'</span>, <span class="st">'753'</span>, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="st">'754'</span>, <span class="st">'755'</span>, <span class="st">'756'</span>, <span class="st">'757'</span>, <span class="st">'758'</span>, <span class="st">'759'</span>, <span class="st">'760'</span>, <span class="st">'761'</span>, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="st">'762'</span>, <span class="st">'763'</span>, <span class="st">'764'</span>, <span class="st">'765'</span>, <span class="st">'766'</span>, <span class="st">'767'</span>, <span class="st">'768'</span>, <span class="st">'769'</span>, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="st">'770'</span>, <span class="st">'771'</span>, <span class="st">'772'</span>, <span class="st">'773'</span>, <span class="st">'774'</span>, <span class="st">'775'</span>, <span class="st">'776'</span>, <span class="st">'777'</span>, </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="st">'778'</span>, <span class="st">'779'</span>, <span class="st">'780'</span>, <span class="st">'781'</span>, <span class="st">'782'</span>, <span class="st">'783'</span>, <span class="st">'784'</span>, <span class="st">'785'</span>, </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="st">'786'</span>, <span class="st">'787'</span>, <span class="st">'788'</span>, <span class="st">'789'</span>, <span class="st">'790'</span>, <span class="st">'791'</span>, <span class="st">'792'</span>, <span class="st">'793'</span>, </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="st">'794'</span>, <span class="st">'795'</span>, <span class="st">'796'</span>, <span class="st">'797'</span>, <span class="st">'798'</span>, <span class="st">'799'</span>)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>outside_state_zc <span class="op">=</span> (<span class="st">'700'</span>, <span class="st">'701'</span>, <span class="st">'703'</span>, <span class="st">'704'</span>, <span class="st">'705'</span>, </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="st">'706'</span>, <span class="st">'707'</span>, <span class="st">'708'</span>, <span class="st">'710'</span>, <span class="st">'711'</span>, <span class="st">'712'</span>, <span class="st">'713'</span>, <span class="st">'714'</span>, </span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="st">'716'</span>, <span class="st">'717'</span>, <span class="st">'718'</span>, <span class="st">'719'</span>, <span class="st">'720'</span>, <span class="st">'721'</span>, <span class="st">'722'</span>, <span class="st">'723'</span>, </span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="st">'724'</span>, <span class="st">'725'</span>, <span class="st">'726'</span>, <span class="st">'727'</span>, <span class="st">'728'</span>, <span class="st">'729'</span>, <span class="st">'730'</span>, <span class="st">'731'</span>, </span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="st">'734'</span>, <span class="st">'735'</span>, <span class="st">'736'</span>, <span class="st">'737'</span>, <span class="st">'738'</span>, <span class="st">'739'</span>, <span class="st">'740'</span>, <span class="st">'741'</span>, </span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="st">'743'</span>, <span class="st">'744'</span>, <span class="st">'745'</span>, <span class="st">'746'</span>, <span class="st">'748'</span>, <span class="st">'749'</span>, <span class="st">'870'</span>, <span class="st">'871'</span>, </span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="st">'873'</span>, <span class="st">'874'</span>, <span class="st">'875'</span>, <span class="st">'877'</span>, <span class="st">'878'</span>, <span class="st">'879'</span>, <span class="st">'880'</span>, <span class="st">'881'</span>, </span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a><span class="st">'882'</span>, <span class="st">'883'</span>, <span class="st">'884'</span>, <span class="st">'885'</span>) </span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a><span class="co">"""Filter centroids for TX zip codes"""</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>zips_texas_centroids <span class="op">=</span> zips_all_centroids[zips_all_centroids[</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ZCTA5'</span>].<span class="bu">str</span>.startswith(texas_zc)]</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="co">"""Filter centroids for border states' zip codes"""</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>zips_texas_borderstates_centroids <span class="op">=</span> zips_all_centroids[zips_all_centroids[</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ZCTA5'</span>].<span class="bu">str</span>.startswith(outside_state_zc)]</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="co">"""Retrieve the unique count of TX zip codes """</span></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>unique_texas_zips <span class="op">=</span> zips_texas_centroids[<span class="st">'ZCTA5'</span>].nunique()</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a><span class="co">"""Retrieve the unique count of border states' zip codes """</span></span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>unique_texas_borderstates_zips <span class="op">=</span> zips_texas_borderstates_centroids[<span class="st">'ZCTA5'</span>].nunique()</span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(unique_texas_zips)</span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(unique_texas_borderstates_zips)</span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a><span class="co">#used chatgpt to debug why I was getting an empty dataframe</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1935
2090</code></pre>
</div>
</div>
<p>The unique Texas zip codes are 1935. The unique Texas’ bordering states zip codes are 2090.</p>
<div id="87b406a5" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""The second part of the problem asking for the function"""</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>TX_polygon <span class="op">=</span> zips_texas_centroids.unary_union</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co">"""Fuction to check if both polygons intersect"""</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> polygons_intersect(poly1, poly2):</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> poly1.intersects(poly2)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co">"""Define the bounding polygons for each neighboring state"""</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>NM <span class="op">=</span> Polygon([(<span class="op">-</span><span class="fl">109.045</span>, <span class="fl">31.332</span>), (<span class="op">-</span><span class="fl">103.002</span>, <span class="fl">31.332</span>), (</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span><span class="fl">103.002</span>, <span class="fl">37.0</span>), (<span class="op">-</span><span class="fl">109.045</span>, <span class="fl">37.0</span>), (<span class="op">-</span><span class="fl">109.045</span>, <span class="fl">31.332</span>)])</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>OK <span class="op">=</span> Polygon([(<span class="op">-</span><span class="fl">103.002</span>, <span class="fl">33.615</span>), (<span class="op">-</span><span class="fl">94.616</span>, <span class="fl">33.615</span>), (</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span><span class="fl">94.616</span>, <span class="fl">37.0</span>), (<span class="op">-</span><span class="fl">103.002</span>, <span class="fl">37.0</span>), (<span class="op">-</span><span class="fl">103.002</span>, <span class="fl">33.615</span>)])</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>AR <span class="op">=</span> Polygon([(<span class="op">-</span><span class="fl">94.617</span>, <span class="fl">33.0</span>), (<span class="op">-</span><span class="fl">89.644</span>, <span class="fl">33.0</span>), (</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span><span class="fl">89.644</span>, <span class="fl">36.499</span>), (<span class="op">-</span><span class="fl">94.617</span>, <span class="fl">36.499</span>), (<span class="op">-</span><span class="fl">94.617</span>, <span class="fl">33.0</span>)])</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>LA <span class="op">=</span> Polygon([(<span class="op">-</span><span class="fl">94.043</span>, <span class="fl">29.993</span>), (<span class="op">-</span><span class="fl">89.747</span>, <span class="fl">29.993</span>), (</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span><span class="fl">89.747</span>, <span class="fl">33.019</span>), (<span class="op">-</span><span class="fl">94.043</span>, <span class="fl">33.019</span>), (<span class="op">-</span><span class="fl">94.043</span>, <span class="fl">29.993</span>)])</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a><span class="co">"""Store each state's polygon with its name in a dictionary"""</span></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>bordering_state_polygons <span class="op">=</span> {</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'New Mexico'</span>: NM,</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Oklahoma'</span>: OK,</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Arkansas'</span>: AR,</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Louisiana'</span>: LA</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a><span class="co">"""Check with bordering states have polygons intersecting with the TX polygon"""</span></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>bordering_states <span class="op">=</span> [state <span class="cf">for</span> state, poly <span class="kw">in</span> bordering_state_polygons.items() <span class="cf">if</span> polygons_intersect(TX_polygon, poly)]</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(bordering_states)</span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a><span class="co">#sources: https://geopandas.org/en/v0.10.0/docs/reference/api/geopandas.GeoSeries.unary_union.html</span></span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a><span class="co">#https://shapely.readthedocs.io/en/stable/reference/shapely.intersects.html</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['New Mexico', 'Oklahoma', 'Arkansas', 'Louisiana']</code></pre>
</div>
</div>
<p>The bordering states are New Mexico, Oklahoma, Arkansa, and Louisiana.</p>
<ol start="3" type="1">
<li>(Partner 2) Then create a subset of zips_texas_borderstates_centroids that contains only the zip codes with at least 1 hospital in 2016. Call the resulting Geo- DataFrame zips_withhospital_centroids What kind of merge did you decide to do, and what variable are you merging on?</li>
</ol>
<div id="4bcefcad" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Filtered hospital data for 2016, count hospitals per ZIP code, and filter for ZIP codes with at least one hospital"""</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>zips_with_hospitals <span class="op">=</span> (combined_hospitals[combined_hospitals[<span class="st">'Year'</span>] <span class="op">==</span> <span class="dv">2016</span>]</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                       .groupby(<span class="st">'ZIP_CD'</span>).size().reset_index(name<span class="op">=</span><span class="st">'Hospital_Count'</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                       .query(<span class="st">'Hospital_Count &gt; 0'</span>))</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co">"""Converted ZIP codes strings"""</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>zips_texas_borderstates_centroids[<span class="st">'ZCTA5'</span>] <span class="op">=</span> zips_texas_borderstates_centroids[</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ZCTA5'</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.zfill(<span class="dv">5</span>)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>zips_with_hospitals[<span class="st">'ZIP_CD'</span>] <span class="op">=</span> zips_with_hospitals[<span class="st">'ZIP_CD'</span>].astype(</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">float</span>).astype(<span class="bu">int</span>).astype(<span class="bu">str</span>).<span class="bu">str</span>.zfill(<span class="dv">5</span>)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="co">"""Performed inner merge centroids of Texas border state ZIP codes with those having hospitals in 2016"""</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>zips_withhospital_centroids <span class="op">=</span> zips_texas_borderstates_centroids.merge(</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>    zips_with_hospitals, left_on<span class="op">=</span><span class="st">'ZCTA5'</span>, right_on<span class="op">=</span><span class="st">'ZIP_CD'</span>, how<span class="op">=</span><span class="st">'inner'</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zips_withhospital_centroids.head())</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a><span class="co">#sources: https://www.geeksforgeeks.org/numpy-size-function-python/</span></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a><span class="co">#https://stackoverflow.com/questions/60669139/inner-and-outer-merge-in-pandas-with-indicator-true</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a><span class="co">#https://stackoverflow.com/questions/53645882/pandas-merging-101</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ZCTA5                    centroid ZIP_CD  Hospital_Count
0  70043  POINT (-89.96276 29.94804)  70043               2
1  70068  POINT (-90.43469 30.13426)  70068               2
2  70119  POINT (-90.08702 29.97574)  70119               3
3  70127  POINT (-89.97675 30.02501)  70127               3
4  70301   POINT (-90.74089 29.8141)  70301               1</code></pre>
</div>
</div>
<p>I decided to do an inner merge since there is a zip code column that exists between both zips_texas_borderstates_centroids and zips_with_hospitals. The variable I performed the merge on is ZCTA5 column from the zips_texas_borderstates_centroids and the ZIP_CD column from zips_with_hospitals.</p>
<ol start="4" type="1">
<li>(Partner 2) For each zip code in zips_texas_centroids, calculate the distance to the nearest zip code with at least one hospital in zips_withhospital_centroids.</li>
</ol>
<ol type="a">
<li>This is a computationally-intensive join. Before attempting to do the entire join, subset to 10 zip codes in zips_texas_centroids and try the join. How long did it take? Approximately how long do you estimate the entire procedure will take?</li>
</ol>
<div id="de6c88b1" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Set the centroid column as the geometry for each GeoDataFrame"""</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>zips_texas_centroids <span class="op">=</span> zips_texas_centroids.set_geometry(<span class="st">'centroid'</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>zips_withhospital_centroids <span class="op">=</span> zips_withhospital_centroids.set_geometry(<span class="st">'centroid'</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co">"""Took a random sample of ten zip codes from TX data"""</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>zips_texas_sample <span class="op">=</span> zips_texas_centroids.sample(<span class="dv">10</span>)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co">"""Performed the timing for how long it takes to run the code on this sample"""</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>start_time <span class="op">=</span> time.time()</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>distances <span class="op">=</span> []</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="co">"""Went through each zip code in our sample"""</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> idx, texas_zip <span class="kw">in</span> zips_texas_sample.iterrows():</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>    min_distance <span class="op">=</span> zips_withhospital_centroids.distance(texas_zip[<span class="st">'centroid'</span>]).<span class="bu">min</span>()</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>    distances.append((texas_zip[<span class="st">'ZCTA5'</span>], min_distance.item())) </span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="co">"""Stopped timing now that loop is done and calculated how long it took"""</span></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>end_time <span class="op">=</span> time.time()</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>sample_duration <span class="op">=</span> end_time <span class="op">-</span> start_time</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a><span class="co">"""Took an estimate the time it take to calculate distances for all zip codes"""</span></span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>estimated_total_time <span class="op">=</span> sample_duration <span class="op">*</span> (<span class="bu">len</span>(</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>    zips_texas_centroids) <span class="op">/</span> <span class="bu">len</span>(zips_texas_sample))</span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(distances)</span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sample_duration)</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(estimated_total_time)</span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a><span class="co">#source: https://stackoverflow.com/questions/29217399/convert-list-of-numpy-float64-to-float-in-python-quickly</span></span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a><span class="co">#https://www.w3schools.com/python/ref_dictionary_items.asp</span></span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a><span class="co">#https://www.w3schools.com/python/ref_random_sample.asp</span></span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a><span class="co">#https://www.geeksforgeeks.org/python-time-time-method/</span></span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a><span class="co">#used chatgpt to help debug because I had to convert my float64 to float</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[('76363', 1.0990231493064953), ('76878', 2.768448471112897), ('78558', 5.7290424187214635), ('78247', 4.550816695793746), ('77855', 2.6220432047125066), ('79407', 1.3577984741828257), ('78114', 4.710073842255124), ('78251', 4.750954843163357), ('78061', 5.355348745910721), ('76446', 2.1325675444584)]
0.02669382095336914
5.165254354476929</code></pre>
</div>
</div>
<p>Distances for the sample ZIP codes: [(‘79326’, 0.1493848898581739), (‘76177’, 0.0), (‘77057’, 0.034170077456204526), (‘79414’, 0.03224788972525331), (‘79045’, 0.0), (‘75647’, 0.0), (‘76384’, 0.0), (‘79257’, 0.29374992383069376), (‘77303’, 0.14081554831669735), (‘77433’, 0.09080768340297626)] Time taken for sample of 10 ZIP codes: 0.059233665466308594 seconds Estimated total time for full dataset: 10.80 seconds</p>
<ol start="2" type="a">
<li>Now try doing the full calculation and time how long it takes. How close is it to your estimation?</li>
</ol>
<div id="3ab7d500" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Start a timer to measure how long the entire process takes"""</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>start_time <span class="op">=</span> time.time()</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>full_distances <span class="op">=</span> []</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="co">"""Loop through each TX sip code centroid"""</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> idx, texas_zip <span class="kw">in</span> zips_texas_centroids.iterrows():</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    min_distance <span class="op">=</span> <span class="bu">float</span>(zips_withhospital_centroids.distance(texas_zip[</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">'centroid'</span>]).<span class="bu">min</span>())</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>    full_distances.append((texas_zip[<span class="st">'ZCTA5'</span>], min_distance))</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a><span class="co">"""Stop timer after full loop is done"""</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>end_time <span class="op">=</span> time.time()</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a><span class="co">"""Calculate total time"""</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>full_duration <span class="op">=</span> end_time <span class="op">-</span> start_time</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>full_duration<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>estimated_total_time<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a><span class="co">#source: https://www.geeksforgeeks.org/python-time-time-method/</span></span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a><span class="co">#https://www.w3schools.com/python/ref_func_float.asp</span></span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a><span class="co">#used chatgpt to help debug because I had to convert my float64 to float</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3.96
5.17</code></pre>
</div>
</div>
<p>The actual time was 6.68 seconds but I estimated it at 10.80 seconds.</p>
<ol start="3" type="a">
<li>Look into the .prj file and report which unit it is in. Convert the given unit to miles, using an appropriate conversion you find online (estimates are okay).</li>
</ol>
<div id="cd3be1ce" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>prj_file <span class="op">=</span> <span class="st">"gz_2010_us_860_00_500k.prj"</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>absolute_path_prj <span class="op">=</span> os.path.join(path, prj_file)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(absolute_path_prj, <span class="st">'r'</span>) <span class="im">as</span> <span class="bu">file</span>:</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    prj_contents <span class="op">=</span> <span class="bu">file</span>.read()</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> read_prj_unit(prj_file_path):</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> <span class="bu">open</span>(prj_file_path, <span class="st">'r'</span>) <span class="im">as</span> <span class="bu">file</span>:</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>        prj_text <span class="op">=</span> <span class="bu">file</span>.read()</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="st">"UNIT[</span><span class="ch">\"</span><span class="st">Meter</span><span class="ch">\"</span><span class="st">"</span> <span class="kw">in</span> prj_text:</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>        unit <span class="op">=</span> <span class="st">"meters"</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="st">"UNIT[</span><span class="ch">\"</span><span class="st">Foot</span><span class="ch">\"</span><span class="st">"</span> <span class="kw">in</span> prj_text <span class="kw">or</span> <span class="st">"UNIT[</span><span class="ch">\"</span><span class="st">Foot_US</span><span class="ch">\"</span><span class="st">"</span> <span class="kw">in</span> prj_text:</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>        unit <span class="op">=</span> <span class="st">"feet"</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="st">"UNIT[</span><span class="ch">\"</span><span class="st">Degree</span><span class="ch">\"</span><span class="st">"</span> <span class="kw">in</span> prj_text:</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>        unit <span class="op">=</span> <span class="st">"degrees"</span></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>        unit <span class="op">=</span> <span class="st">"unknown"</span></span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> unit</span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>unit <span class="op">=</span> read_prj_unit(absolute_path_prj)</span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(unit)</span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a><span class="co">#source: https://www.digitalocean.com/community/tutorials/python-valueerror-exception-handling-examples</span></span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a><span class="co">#https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>degrees</code></pre>
</div>
</div>
<p>The unit in the .prj file is degrees. The conversion from degrees to miles is that one degree is 69 miles.</p>
<p>#source: https://www.usgs.gov/faqs/how-much-distance-does-a-degree-minute-and-second-cover-your-maps#:~:text=One%20degree%20of%20latitude%20equals,one%2Dsecond%20equals%20101%20feet.</p>
<ol start="5" type="1">
<li>(Partner 2) Calculate the average distance to the nearest hospital for each zip code in Texas. What unit is this in? Report the average distance in miles. Does this value make sense? Map the value for each zip code.</li>
</ol>
<div id="f68c461f" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Function to determine the unit from the .prj file content"""</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_prj_unit(prj_text):</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="st">"UNIT[</span><span class="ch">\"</span><span class="st">Degree</span><span class="ch">\"</span><span class="st">"</span> <span class="kw">in</span> prj_text:</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"degrees"</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="st">"UNIT[</span><span class="ch">\"</span><span class="st">Meter</span><span class="ch">\"</span><span class="st">"</span> <span class="kw">in</span> prj_text:</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"meters"</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="st">"UNIT[</span><span class="ch">\"</span><span class="st">Foot</span><span class="ch">\"</span><span class="st">"</span> <span class="kw">in</span> prj_text <span class="kw">or</span> <span class="st">"UNIT[</span><span class="ch">\"</span><span class="st">Foot_US</span><span class="ch">\"</span><span class="st">"</span> <span class="kw">in</span> prj_text:</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"feet"</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"unknown"</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>unit <span class="op">=</span> get_prj_unit(prj_contents)</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>unit<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a><span class="co">"""Function to convert distance to miles based on the detected unit"""</span></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> convert_distance_to_miles(distance, unit):</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>    METER_TO_MILE <span class="op">=</span> <span class="fl">1609.34</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>    FOOT_TO_MILE <span class="op">=</span> <span class="dv">5280</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>    MILES_PER_DEGREE <span class="op">=</span> <span class="fl">69.0</span>  </span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> unit <span class="op">==</span> <span class="st">"meters"</span>:</span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> distance <span class="op">/</span> METER_TO_MILE</span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> unit <span class="op">==</span> <span class="st">"feet"</span>:</span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> distance <span class="op">/</span> FOOT_TO_MILE</span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> unit <span class="op">==</span> <span class="st">"degrees"</span>:</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> distance <span class="op">*</span> MILES_PER_DEGREE</span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"Unknown unit; cannot convert to miles."</span>)</span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a>texas_zip_prefixes <span class="op">=</span> [</span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">'733'</span>, <span class="st">'750'</span>, <span class="st">'751'</span>, <span class="st">'752'</span>, <span class="st">'753'</span>, <span class="st">'754'</span>, <span class="st">'755'</span>, <span class="st">'756'</span>, <span class="st">'757'</span>, <span class="st">'758'</span>, <span class="st">'759'</span>, <span class="st">'760'</span>, <span class="st">'761'</span>, <span class="st">'762'</span>, </span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">'763'</span>, <span class="st">'764'</span>, <span class="st">'765'</span>, <span class="st">'766'</span>, <span class="st">'767'</span>, <span class="st">'768'</span>, <span class="st">'769'</span>, <span class="st">'770'</span>, <span class="st">'771'</span>, <span class="st">'772'</span>, <span class="st">'773'</span>, <span class="st">'774'</span>, <span class="st">'775'</span>, <span class="st">'776'</span>, </span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">'777'</span>, <span class="st">'778'</span>, <span class="st">'779'</span>, <span class="st">'780'</span>, <span class="st">'781'</span>, <span class="st">'782'</span>, <span class="st">'783'</span>, <span class="st">'784'</span>, <span class="st">'785'</span>, <span class="st">'786'</span>, <span class="st">'787'</span>, <span class="st">'788'</span>, <span class="st">'789'</span>, <span class="st">'790'</span>, </span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">'791'</span>, <span class="st">'792'</span>, <span class="st">'793'</span>, <span class="st">'794'</span>, <span class="st">'795'</span>, <span class="st">'796'</span>, <span class="st">'797'</span>, <span class="st">'798'</span>, <span class="st">'799'</span></span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a>census[<span class="st">'ZCTA5'</span>] <span class="op">=</span> census[<span class="st">'ZCTA5'</span>].astype(<span class="bu">str</span>)</span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a>texas_zips <span class="op">=</span> census[census[<span class="st">'ZCTA5'</span>].<span class="bu">str</span>[:<span class="dv">3</span>].isin(texas_zip_prefixes)]</span>
<span id="cb40-38"><a href="#cb40-38" aria-hidden="true" tabindex="-1"></a>texas_zips[<span class="st">'centroid'</span>] <span class="op">=</span> texas_zips.geometry.centroid</span>
<span id="cb40-39"><a href="#cb40-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-40"><a href="#cb40-40" aria-hidden="true" tabindex="-1"></a>combined_hospitals[<span class="st">'ZIP_CD'</span>] <span class="op">=</span> combined_hospitals[<span class="st">'ZIP_CD'</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.split(<span class="st">'.'</span>).<span class="bu">str</span>[<span class="dv">0</span>]</span>
<span id="cb40-41"><a href="#cb40-41" aria-hidden="true" tabindex="-1"></a>texas_hospitals <span class="op">=</span> texas_zips[texas_zips[<span class="st">'ZCTA5'</span>].isin(combined_hospitals[<span class="st">'ZIP_CD'</span>])]</span>
<span id="cb40-42"><a href="#cb40-42" aria-hidden="true" tabindex="-1"></a>texas_hospitals <span class="op">=</span> texas_hospitals.set_geometry(<span class="st">'centroid'</span>)  </span>
<span id="cb40-43"><a href="#cb40-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-44"><a href="#cb40-44" aria-hidden="true" tabindex="-1"></a><span class="co">"""Calculate distances to the nearest hospital for each Texas ZIP code"""</span></span>
<span id="cb40-45"><a href="#cb40-45" aria-hidden="true" tabindex="-1"></a>distances <span class="op">=</span> []</span>
<span id="cb40-46"><a href="#cb40-46" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _, zip_row <span class="kw">in</span> texas_zips.iterrows():</span>
<span id="cb40-47"><a href="#cb40-47" aria-hidden="true" tabindex="-1"></a>    zip_centroid <span class="op">=</span> zip_row[<span class="st">'centroid'</span>]</span>
<span id="cb40-48"><a href="#cb40-48" aria-hidden="true" tabindex="-1"></a>    min_distance <span class="op">=</span> texas_hospitals.distance(zip_centroid).<span class="bu">min</span>()</span>
<span id="cb40-49"><a href="#cb40-49" aria-hidden="true" tabindex="-1"></a>    min_distance_miles <span class="op">=</span> convert_distance_to_miles(min_distance, unit)</span>
<span id="cb40-50"><a href="#cb40-50" aria-hidden="true" tabindex="-1"></a>    distances.append(min_distance_miles)</span>
<span id="cb40-51"><a href="#cb40-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-52"><a href="#cb40-52" aria-hidden="true" tabindex="-1"></a>texas_zips[<span class="st">'nearest_hospital_distance_miles'</span>] <span class="op">=</span> distances</span>
<span id="cb40-53"><a href="#cb40-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-54"><a href="#cb40-54" aria-hidden="true" tabindex="-1"></a><span class="co">"""Calculate the average distance"""</span></span>
<span id="cb40-55"><a href="#cb40-55" aria-hidden="true" tabindex="-1"></a>average_distance <span class="op">=</span> texas_zips[<span class="st">'nearest_hospital_distance_miles'</span>].mean()</span>
<span id="cb40-56"><a href="#cb40-56" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>average_distance<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb40-57"><a href="#cb40-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-58"><a href="#cb40-58" aria-hidden="true" tabindex="-1"></a><span class="co">"""Plotted map"""</span></span>
<span id="cb40-59"><a href="#cb40-59" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb40-60"><a href="#cb40-60" aria-hidden="true" tabindex="-1"></a>texas_zips.plot(</span>
<span id="cb40-61"><a href="#cb40-61" aria-hidden="true" tabindex="-1"></a>    column<span class="op">=</span><span class="st">'nearest_hospital_distance_miles'</span>,</span>
<span id="cb40-62"><a href="#cb40-62" aria-hidden="true" tabindex="-1"></a>    legend<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb40-63"><a href="#cb40-63" aria-hidden="true" tabindex="-1"></a>    legend_kwds<span class="op">=</span>{<span class="st">'label'</span>: <span class="st">"Miles to Nearest Hospital"</span>},</span>
<span id="cb40-64"><a href="#cb40-64" aria-hidden="true" tabindex="-1"></a>    ax<span class="op">=</span>ax,</span>
<span id="cb40-65"><a href="#cb40-65" aria-hidden="true" tabindex="-1"></a>    edgecolor<span class="op">=</span><span class="st">"black"</span>,</span>
<span id="cb40-66"><a href="#cb40-66" aria-hidden="true" tabindex="-1"></a>    cmap<span class="op">=</span><span class="st">'viridis'</span></span>
<span id="cb40-67"><a href="#cb40-67" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-68"><a href="#cb40-68" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Average Distance to Nearest Hospital for Texas ZIP Codes'</span>)</span>
<span id="cb40-69"><a href="#cb40-69" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">'off'</span>)</span>
<span id="cb40-70"><a href="#cb40-70" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb40-71"><a href="#cb40-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-72"><a href="#cb40-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-73"><a href="#cb40-73" aria-hidden="true" tabindex="-1"></a><span class="co">#source: https://www.geeksforgeeks.org/how-to-remove-all-decimals-from-a-number-using-python/#</span></span>
<span id="cb40-74"><a href="#cb40-74" aria-hidden="true" tabindex="-1"></a><span class="co">#https://stackoverflow.com/questions/22231592/pandas-change-data-type-of-series-to-string</span></span>
<span id="cb40-75"><a href="#cb40-75" aria-hidden="true" tabindex="-1"></a><span class="co">#https://stackoverflow.com/questions/53645882/pandas-merging-101</span></span>
<span id="cb40-76"><a href="#cb40-76" aria-hidden="true" tabindex="-1"></a><span class="co">#https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.set_crs.html</span></span>
<span id="cb40-77"><a href="#cb40-77" aria-hidden="true" tabindex="-1"></a><span class="co">#https://www.geopostcodes.com/blog/how-to-calculate-distance-between-two-zip-codes-in-python/</span></span>
<span id="cb40-78"><a href="#cb40-78" aria-hidden="true" tabindex="-1"></a><span class="co"># Use Chatgpt to debug because I kept getting zero miles</span></span>
<span id="cb40-79"><a href="#cb40-79" aria-hidden="true" tabindex="-1"></a><span class="co">#lecture 9 from class</span></span>
<span id="cb40-80"><a href="#cb40-80" aria-hidden="true" tabindex="-1"></a><span class="co">#used chatgpt because my plot was showing blank at first</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>degrees
8.83</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="ps4_final_files/figure-html/cell-26-output-2.png" width="533" height="417" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>It is in degrees. The average distance to the nearest hospital for Texas zip codes is 8.83 miles. It does make sense considering that Texas is a big state with a wide geographic spread so there is a mixture of both densely populated urban areas and rural areas where hospitals might be spaced further apart. However, it also does have major urban centers like Austin and Houston with lots of nearby hospitals, reducing the average. So it makes sense to have an average distance of 8.83 miles.</p>
</section>
<section id="effects-of-closures-on-access-in-texas-15-pts" class="level2">
<h2 class="anchored" data-anchor-id="effects-of-closures-on-access-in-texas-15-pts">Effects of closures on access in Texas (15 pts)</h2>
<ol type="1">
<li>(Partner 1) Using the corrected hospital closures dataset from the first section, create a list of directly affected zip codes in Texas – that is, those with at least one closure in 2016-2019. Display a table of the number of zip codes vs.&nbsp;the number of closures they experienced.</li>
</ol>
<div id="c6c8e6a9" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Cross referencing zipcodes to include only Texas"""</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>true_suspected_closures_df[<span class="st">'Zipcode'</span>] <span class="op">=</span> true_suspected_closures_df[</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Zipcode'</span>].astype(<span class="bu">int</span>).astype(<span class="bu">str</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>tx_closures <span class="op">=</span> true_suspected_closures_df[true_suspected_closures_df[</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Zipcode'</span>].isin(tx_zip[<span class="st">'ZCTA5'</span>])]</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co">"""Grouping closures by zipcode"""</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>closures_by_zip <span class="op">=</span> tx_closures.groupby(<span class="st">'Zipcode'</span>).size().reset_index(</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>    name<span class="op">=</span><span class="st">'Number of Closures'</span>)</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>closures_summary <span class="op">=</span> closures_by_zip.sort_values(by<span class="op">=</span><span class="st">'Number of Closures'</span>)</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(closures_summary)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>total_zip_codes <span class="op">=</span> closures_summary.shape[<span class="dv">0</span>]</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>total_closures <span class="op">=</span> closures_summary[<span class="st">'Number of Closures'</span>].<span class="bu">sum</span>()</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>total_zip_codes</span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>total_closures</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Zipcode  Number of Closures
0    75042                   1
25   79553                   1
24   79529                   1
23   79520                   1
22   78834                   1
21   78734                   1
20   78613                   1
19   78336                   1
18   78061                   1
17   78017                   1
16   77429                   1
15   77065                   1
14   77035                   1
13   76645                   1
12   76531                   1
11   76520                   1
10   76502                   1
9    75862                   1
8    75835                   1
7    75662                   1
6    75601                   1
5    75390                   1
4    75235                   1
3    75140                   1
2    75087                   1
1    75051                   1
26   79735                   1
27   79902                   1</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>np.int64(28)</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>(Partner 1) Plot a choropleth of which Texas zip codes were directly affected by a closure in 2016-2019 – there was at least one closure within the zip code. How many directly affected zip codes are there in Texas?</li>
</ol>
<div id="15952e52" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Merging on zipcodes and filling data gaps in new column"""</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>tx_zip_hospitals_closure <span class="op">=</span> tx_zip.merge(closures_by_zip, left_on<span class="op">=</span><span class="st">'ZCTA5'</span>, </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>    right_on<span class="op">=</span><span class="st">'Zipcode'</span>, how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>tx_zip_hospitals_closure[<span class="st">'Number of Closures'</span>] <span class="op">=</span> tx_zip_hospitals_closure[</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Number of Closures'</span>].fillna(<span class="dv">0</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> tx_zip_hospitals_closure.plot(column<span class="op">=</span><span class="st">'Number of Closures'</span>, legend<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Texas Zipcodes Affected by Hospital Closures (2016-2019)'</span>)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">'off'</span>) </span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>affected_zip_codes_count <span class="op">=</span> closures_by_zip[<span class="st">'Zipcode'</span>].nunique()</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(affected_zip_codes_count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="ps4_final_files/figure-html/cell-28-output-1.png" width="522" height="417" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>28</code></pre>
</div>
</div>
<p>There are 28 directly affect zipcodes in Texas.</p>
<ol start="3" type="1">
<li>(Partner 1) Then identify all the indirectly affected zip codes: Texas zip codes within a 10-mile radius of the directly affected zip codes. To do so, first create a GeoDataFrame of the directly affected zip codes. Then create a 10-mile buffer around them. Then, do a spatial join with the overall Texas zip code shapefile. How many indirectly affected zip codes are there in Texas?</li>
</ol>
<div id="93eb8194" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Fixing data to match crs = EPSG:32614"""</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>tx_zip <span class="op">=</span> tx_zip.to_crs(<span class="st">"EPSG:32614"</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>tx_zip_hospitals_closure <span class="op">=</span> tx_zip_hospitals_closure.to_crs(<span class="st">"EPSG:32614"</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="co">"""Identifying directly affected zipcodes"""</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>directly_affected_gdf <span class="op">=</span> tx_zip_hospitals_closure[tx_zip_hospitals_closure[<span class="st">'Number of Closures'</span>] <span class="op">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="co">"""Creating buffer for 10 miles multiplying miles by meters - crs is EPSG:32614"""</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>buffer_distance <span class="op">=</span> <span class="dv">10</span> <span class="op">*</span> <span class="fl">1609.34</span> </span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>directly_affected_gdf[<span class="st">'geometry'</span>] <span class="op">=</span> directly_affected_gdf.geometry.<span class="bu">buffer</span>(buffer_distance)</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>indirectly_affected_zip <span class="op">=</span> gpd.sjoin(</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>    tx_zip, directly_affected_gdf, how<span class="op">=</span><span class="st">'inner'</span>, predicate<span class="op">=</span><span class="st">'intersects'</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>indirectly_affected_zip_count <span class="op">=</span> indirectly_affected_zip[<span class="st">'ZCTA5_left'</span>].nunique()</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(indirectly_affected_zip_count)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a><span class="co">#https://epsg.io/32614</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>555</code></pre>
</div>
</div>
<p>There are 555 indirectly affect zipcodes in Texas when we use a 10 mile buffer.</p>
<ol start="4" type="1">
<li>(Partner 1) Make a choropleth plot of the Texas zip codes with a different color for each of the 3 categories: directly affected by a closure, within 10 miles of closure but not directly affected, or not affected.</li>
</ol>
<div id="7e1a4503" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">"""Function categorizing zipcodes"""</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> categorize_zip(row):</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> row[<span class="st">'ZCTA5'</span>] <span class="kw">in</span> directly_affected_gdf[<span class="st">'Zipcode'</span>].astype(<span class="bu">str</span>).values:</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'directly affected'</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> row[<span class="st">'ZCTA5'</span>] <span class="kw">in</span> indirectly_affected_zip[<span class="st">'ZCTA5_left'</span>].astype(<span class="bu">str</span>).values:</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'indirectly affected'</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'not affected'</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>tx_zip[<span class="st">'category'</span>] <span class="op">=</span> tx_zip.<span class="bu">apply</span>(categorize_zip, axis<span class="op">=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="154bc105" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> tx_zip.plot(column<span class="op">=</span><span class="st">'category'</span>, legend<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Texas Zipcodes Impacted by Hospital Closures (2016-2019)'</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">'off'</span>)  </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="ps4_final_files/figure-html/cell-31-output-1.png" width="495" height="423" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="reflecting-on-the-exercise-10-pts" class="level2">
<h2 class="anchored" data-anchor-id="reflecting-on-the-exercise-10-pts">Reflecting on the exercise (10 pts)</h2>
<p>(Partner 1) The “first-pass” method we’re using to address incorrectly identified closures in the data is imperfect. Can you think of some potential issues that could arise still and ways to do a better job at confirming hospital closures?</p>
<p>The “first-pass” method relies on accurate data and recording from hospitals, which can lead to misclassifications resulting in false positives and false negatives. Providing multiple options for the termination code will lead to inconsistent reporting. The data also may not account for or capture new hospitals or all hospitals that have been terminated, so completeness of the data would be an issue. A better job at confirming hospital closures would be to include one binary variable that provides an accurate and consistent definition for hospital closures. Another way to confirm hospital closures would be to cross reference and verify with another source.</p>
<p>(Partner 2) Consider the way we are identifying zip codes affected by closures. How well does this reflect changes in zip-code-level access to hospitals? Can you think of some ways to improve this measure?</p>
<p>There are a few limitations. For example, a hospital closed in a rural area will have a very different effect in a hospital closure in an urban area since a rural hospital closure might impact a lot of nearby zip codes significantly while an urban hopsital closure may only have a small effect because of access to multiple hospitals. Another limitation is that it doesn’t consider demographics. For example, a high-need population like the elderly or low-income may experience more impacts from closures than other groups. Also, we don’t know what of hospital it is. It could be an emergency care, general hospital, or a specialized treatment hopsital. One way to improve this measure would be to do it based on population weight such as figuring out where most people live within a zip code and measuring their access to hospitals. Another improvement would be incorporating demographic data such as age and income because that could help indicate which population would be the most affected by a hospital closure.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>